name: 自动下载词典 → 运行脚本 → 提交结果
on:
  schedule:
    - cron: '0 22 * * *' # UTC 22:00 UTC+8 6:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v6

      - name: 下载解压最新词典 ZIP
        run: |
          mkdir input_dicts
          curl -L "https://github.com/amzxyz/rime_wanxiang/releases/download/dict-nightly/pro-moqi-fuzhu-dicts.zip" \
            -o "input_dicts/wanxiang.zip"
          unzip -q "input_dicts/wanxiang.zip"

      - name: 处理原始词库
        run: |
          python -m pip install --upgrade pip
          pip install tqdm
          mkdir -p output_dicts
          python duofuzhu.py

      - name: 提交输出文件到仓库
        env:
          GIT_AUTHOR_NAME: ci-bot
          GIT_AUTHOR_EMAIL: ci@example.com
          GIT_COMMITTER_NAME: ci-bot
          GIT_COMMITTER_EMAIL: ci@example.com
        run: |
          cp -rf output_dicts/* .
          git add .
          git commit -m "自动更新处理后词库 [ci skip]"
          git push
